### ISSUE TITLE
非常棒的主题，请问暗色模式和亮色模式某些样式不统一是BUG吗？

### ISSUE THREAD

**Issue by ZackYJz** [UNICKCHENG/developer-theme-for-logseq#16]
我在 custom.css 设置了字体和大小
```
body {
 --ls-font-family: 'PingFang','Roboto','fira sans', 'segoe UI Emoji', 'sarasa ui sc', sans-serif !important;
  font-size:.9em;
}
```
但是好像在暗色模式和暗色模式下有些样式不统一，如图：
<img width="445" alt="image" src="https://user-images.githubusercontent.com/58540119/231371060-f9987695-82e1-4e5d-a19f-6bf46f251bc7.png">
<img width="436" alt="image" src="https://user-images.githubusercontent.com/58540119/231371090-166c2d24-b2e6-4249-bad8-9608931d86f7.png">

- 亮色模式下的标题依然是主题默认的中文字体，但暗色模式下就是自己设置的字体
- 亮色模式下的 admontionblock 样式和暗色模式不同
- 亮色模式下代码块有圆角，暗色模式下没有（但readme.md的演示图中的暗色模式有圆角）
请问这些都需要自己手动调整css吗？

**Comment by UNICKCHENG** [comment]
@ZackYJz 

### 1. 「亮色模式下的标题依然是主题默认的中文字体，但暗色模式下就是自己设置的字体」

您可以尝试使用以下方式来定义字体，而非通过 body 

```css
:root {
  --ls-font-family: 'PingFang','Roboto','fira sans', 'segoe UI Emoji', 'sarasa ui sc', sans-serif !important;
  font-size:.9em;
}
```

### 2. 「亮色模式下的 admontionblock 样式和暗色模式不同」

暂时没有做 admontionblock 的适配，可能会存在差异。但是提供的截图似乎与我这边的效果存在出入，可以查看下 `custom.css` 中是否还存在其他配置 

```
#+BEGIN_NOTE
SNOW
#+END_NOTE
```

![image](https://user-images.githubusercontent.com/32270702/231445873-6c29a73d-6b4e-465b-9248-a88763ca7696.png)


### 3. 「亮色模式下代码块有圆角，暗色模式下没有（但readme.md的演示图中的暗色模式有圆角）」

我不确定您的 `custom.css` 中是否还存在其他配置，如果没有的话，可以尝试重启 logseq。

另外请确保 `logseq-developer-theme` 使用的是最新版本，即 `v1.2.5`
