### ISSUE TITLE
fix: ios border-radious Invalid

### ISSUE THREAD

**Issue by UNICKCHENG** [UNICKCHENG/developer-theme-for-logseq#3]
- release version: latest
- os: ios

I've tried adding the following code to [_code.scss](https://github.com/UNICKCHENG/logseq-developer-theme/blob/main/scss/_code.scss), but it still doesn't seem to work on iphone and ipad
```scss
@mixin bordeRadius() {
    -webkit-border-radius: 10px !important; // Safari 3-4, iOS 1-3.2, Android 1.6-
    -moz-border-radius: 10px !important;    // Firefox 1-3.6 
    -khtml-border-radius: 10px !important;  // Konqueror
    border-radius: 10px !important;         // Opera 10.5, IE 9, Safari 5, Chrome, Firefox 4, iOS 4, Android 2.1+
}

.CodeMirror, 
.CodeMirror-scroll .CodeMirror-sizer ,
.CodeMirror-code .CodeMirror-linenumber {
    font-family: var(--ct-code-font-family);
    box-shadow: none;
    text-shadow: none !important;
    @include bordeRadius();
}

// 背景样式
.CodeMirror-scroll .CodeMirror-sizer,
.cm-s-solarized.cm-s-dark {
    background: var(--ls-code-background-color) !important;
    color: var(--ls-code-color) !important;
    @include bordeRadius();
    }
//  序号样式
.CodeMirror, .CodeMirror-scroll .CodeMirror-gutters,
.CodeMirror-code .CodeMirror-linenumber,
.cm-s-solarized.cm-s-dark .CodeMirror-gutters {
    color: var(--ls-third-theme-color) ;
    background: var(--ls-code-background-color) !important;
    @include bordeRadius();
}
```
Extra attempts: it seems that many people have mentioned `overflow: hidden`, but this brings me to a new problem with some `div` being hidden

## Screenshots
![4109E3C1-EC4D-4363-8C86-A2E839E2B59D](https://user-images.githubusercontent.com/32270702/207764844-d4196692-5162-4832-ae79-6f016bb7ef9f.jpeg)
