### ISSUE TITLE
页面的滚动条没有了，可以添加有滚动条的版本吗？

### ISSUE THREAD

**Issue by lee88688** [UNICKCHENG/developer-theme-for-logseq#31]

**Comment by UNICKCHENG** [comment]
@lee88688  页面滚动条是刻意隐藏掉的（部分设置页面是还保留的）。如果你希望保留页面滚动条可以试试下面的方案

在 `logseq/custom.css` 中添加以下代码
```css
body[data-page="all-journals"] #main-content-container::-webkit-scrollbar,
body[data-page="home"] #main-content-container::-webkit-scrollbar,
body[data-page="page"] #main-content-container::-webkit-scrollbar,
.menu-links-wrapper::-webkit-scrollbar {
    display: unset;
}
body[data-page="all-journals"] #main-content-container
body[data-page="home"] #main-content-container,
body[data-page="page"] #main-content-container,
.menu-links-wrapper {
    scrollbar-width: unset; /* Firefox */
    -ms-overflow-style: unset; /* IE 10+ */
    overflow-x: unset;
    overflow-y: unset;
}
```
