### ISSUE TITLE
有幸第一时间更新v1.2.17，我想知道如何设置该主题的字体和字体大小?

### ISSUE THREAD

**Issue by igeekbb** [UNICKCHENG/developer-theme-for-logseq#56]
Fortunate to update to v1.2.17 for the first time, I'm curious about how to set the font and font size for this theme?

**Comment by UNICKCHENG** [comment]
@igeekbb  比较遗憾，目前 logseq 不支持通过界面来设置字体样式。不过可以试试配置 `custom.css` 来实现 

![image](https://github.com/UNICKCHENG/logseq-developer-theme/assets/32270702/c63e3eea-1b7b-42e4-ba8e-528bf158c048)

![image](https://github.com/UNICKCHENG/logseq-developer-theme/assets/32270702/b1cc9a56-faae-4a1b-9e1d-7891b570ae6f)

```css
:root {
   // 自定义字体，
    --ls-font-family: apple-font, common-font, code-font, ui-font, system-ui !important;

   // 自定义字体大小 
    font-size: 11px; 
}
```

> 注：字体大小的调整也可通过放缩界面来达到效果，如按住 `ctrl` + `+` (加号键) 来实现。按住 `ctrl` + `0` 可还原为默认大小

可参考
- https://github.com/logseq/logseq/discussions/5146

**Comment by igeekbb** [comment]
非常感谢，我发现通过以上代码，可以实现字体大小设置，但正文字体大小并不会改变，只会改变菜单文字大小，这代码在其它主题设置并不会发生此问题。

**Comment by UNICKCHENG** [comment]
> 非常感谢，我发现通过以上代码，可以实现字体大小设置，但正文字体大小并不会改变，只会改变菜单文字大小，这代码在其它主题设置并不会发生此问题。

@igeekbb 是的，有些字体大小被配置成固定值了，如标题。建议改用 `zoom` 来进行界面放缩，而不是`font-size`来配置，避免破坏不同字体样式之间的相对大小。

```css
:root {
    // 自定义放缩比例
    zoom:120%;
}
```
